language: node_js
node_js:
  - "stable"

dist: jammy

cache:
  directories:
    - "node_modules"
services:
  - postgresql

before_install:
  - npm i -g npm@latest --no-audit
install:
  - npm ci --no-audit
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - npm run test
  - npm run lint

after_success: npm run coverage
