services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports: 
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: josmwafrika789
      POSTGRES_USER: postgres
      POSTGRES_DB: shift_db_dev
      POSTGRES_HOST: postgres
    volumes:
      - 'backend-db:/var/lib/postgresql/data'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M
    networks:
      - application

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: compose_node 
    container_name: backend
    volumes:
      - './:/app'
    ports:
      - '5000:5000'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M
    networks:
      - application
      
networks:
  application:
    driver: bridge
volumes:
  backend-db: